version: '3.8'

services:
  app:
    build: .
    command: npm run dev
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - wiremock
      - db

  wiremock:
    image: wiremock/wiremock:2.35.0
    ports:
      - "8080:8080"
    volumes:
      - ./wiremock:/home/wiremock
    command: --verbose

volumes:
  mongo_data:
